name: Deploy to S3

on:
  push:
    branches:
      - main # ou a branch que desejar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # substitua pela sua região

      - name: Deploy arquivos para S3
        run: |
          aws s3 sync . s3://app.junior.tec.br --delete --exclude ".git/*" --exclude ".github/*" --acl public-read
